### ISSUE TITLE
Hi, I found typing mistake!!

### ISSUE THREAD

**Issue by SSong-develop** [skydoves/android-developer-roadmap#1]
I'm looking at your roadmap well.
But In App Navigation Part, Fragments
(Fragmetn Transcations) -> (Fragment Transactions), i think it is collect typing. 
Thanks for watch my issues👍
(P.S, I really really helpful for watch your project & opensources. So I always rooting for you. Thanks for your tect skills...??❤)

**Comment by skydoves** [comment]
Awesome! It's really good to hear that. :)
Thank you for reporting the typo issue. 😄

**Comment by skydoves** [comment]
Fixed on #3
