### ISSUE TITLE
KTOR missing in Network Layer

### ISSUE THREAD

**Issue by iamAliRaza** [skydoves/android-developer-roadmap#10]
Need to add KTOR in network layer...

**Comment by skydoves** [comment]
Hey @iamAliRaza,
Thanks for giving your idea. I'm not thinking KOTR is used to develop an Android application. 😄

**Comment by iamAliRaza** [comment]
@skydoves 😄its not about your thinking then don't add **Retrofit** and some other **third party libraries** as well.  We also don't need those for developing Android application. We can use old school HttpClient which already comes with Android SDK. 

Happy Coding

**Comment by skydoves** [comment]
Hey @iamAliRaza, sorry for my bad.😅  I was thinking KOTR is generally used to develop the backend side much more than the client-side. If my thinking is wrong please correct me. Maybe is it better to replace the Volley with KTOR?

**Comment by mateuszteteruk** [comment]
We can use Ktor on Android without any hassle. It's multiplatform, we can use it anywhere :) especially in Kotlin Multiplatform Mobile

**Comment by skydoves** [comment]
Hey folks, thanks for sharing your opinions! I just updated the network layout with `Ktor`. 😄
