### ISSUE TITLE
Small typo in roadmap

### ISSUE THREAD

**Issue by ozh-dev** [skydoves/android-developer-roadmap#17]
Dimnes -> Dimens?

![image](https://user-images.githubusercontent.com/8090222/145172372-4b27d9a5-cfeb-4ad6-9f6d-543619118ea0.png)

**Comment by skydoves** [comment]
Hey @ozh-dev, thanks for reporting the typo! 
It's updated (f8dd1e4e7a).

**Comment by ozh-dev** [comment]
You are welcome 👍
