### ISSUE TITLE
Add Japanese & Chinese as extra languages of README 

### ISSUE THREAD

**Issue by masah517** [skydoves/android-developer-roadmap#40]
Hi! I would like to add Japanese & Chinese as additional languages for README. 
Please let me know if there will be any problem, thank you.

**Comment by skydoves** [comment]
Hey @masah517, I'd really appreciate it if you could contribute to these two languages. Thanks!

**Comment by skydoves** [comment]
@masah517 I’d like to notify you - The Chinese translation was added in #41

**Comment by masah517** [comment]
@skydoves 
Noted! Thank you for the reminder!
I will do the Japanese part only
