### ISSUE TITLE
Feature Request: Add build tools and CI/CD

### ISSUE THREAD

**Issue by TylerMcCraw** [skydoves/android-developer-roadmap#7]
Some examples below

Consider adding build tools:
- Gradle > Groovy or KTS
- Bazel

Consider adding CI/CD tools such as:
- Bitrise
- Circle CI
- Jenkins

**Comment by MahmoudMabrok** [comment]
for  CI/CD, we have Github Action which we are using their service now

**Comment by skydoves** [comment]
Hey guys, added the CI/CI section. Thanks for sharing your ideas! 😃
