### ISSUE TITLE
Feature request: More testing

### ISSUE THREAD

**Issue by mateuszteteruk** [skydoves/android-developer-roadmap#9]
Hey, I would like to suggest adding few libraries related to testing.

Regarding mocking, I think it's better to use [Mockk](https://mockk.io/) instead of Mockito - better Kotlin support.

Regarding assertions, there is also [assertk](https://github.com/willowtreeapps/assertk). We can choose assertion tool based on our personal preferences. 

I think it's also important to mention [Kaspresso](https://github.com/KasperskyLab/Kaspresso) for UI Testing. It's based on Espresso and UI Automator but has a lot better Kotlin support :)

What do you think?

**Comment by MahmoudMabrok** [comment]
i agree with @mateuszteteruk  these are kotlin solutions and more powerful.

**Comment by skydoves** [comment]
Hey guys, added more testing branches (Unit Test + Android Test). Thanks for sharing your ideas! 😃
